### ユーザー情報取得
GET http://localhost:8000/api/users/1
Accept: application/json
Authorization: Bearer 7|CeNpJO7LX2GQQERWTeZhHt21nZP2AJcsaf89wugT06972d66

### ユーザー一覧取得(level)
GET http://localhost:8000/api/users?min_level=3&max_level=9
Accept: application/json

### アイテム一覧取得
GET http://localhost:8000/api/item
Accept: application/json

### ユーザー登録(Azure)
POST https://api-juelhunter.japaneast.cloudapp.azure.com/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "kida"
}

### ユーザー登録(local)
POST http://localhost:8000/api/users/store
Content-Type: application/json
Accept: application/json
Authorization: Bearer 1|0QkCf5MrjreqkyYH7QI8BWZ8MAO8YMQpgL0yQVms80a49f8b //ユーザー認証

{
    "name": "jobi2"
}

### 既存ユーザーのトークン生成(local)
POST http://localhost:8000/api/users/createToken
Content-Type: application/json
Accept: application/json

{
    "user_id": 1
}

### ユーザー更新
POST http://localhost:8000/api/users/update/105
Content-Type: application/json
Accept:application/json
Authorization: Bearer 1|0QkCf5MrjreqkyYH7QI8BWZ8MAO8YMQpgL0yQVms80a49f8b //ユーザー認証

{
    "name": "super_jobi"
}

### フレンドリスト
GET  http://localhost:8000/api/friend/index
Content-Type: application/json
Accept:application/json

### ランキング取得
GET https://api-juelhunter.japaneast.cloudapp.azure.com/api/ranking/index/1
Content-Type: application/json
Accept:application/json
Authorization: Bearer 1|jqAqMtjsDA20JMJHwKn5w6FKCI1iRJjVaDwOftGQ396a594c //ユーザー認証

### ランキング登録
POST https://api-juelhunter.japaneast.cloudapp.azure.com/api/ranking/store
Content-Type: application/json
Accept:application/json
Authorization: Bearer 1|jqAqMtjsDA20JMJHwKn5w6FKCI1iRJjVaDwOftGQ396a594c

{
    "user_id": 1,
    "stage_id": 1,
    "score": 100
}
