### ユーザー情報取得
GET https://api-juelhunter.japaneast.cloudapp.azure.com/api/users/102
Accept: application/json

### ユーザー一覧取得(level)
GET http://localhost:8000/api/users?min_level=3&max_level=9
Accept: application/json

### アイテム一覧取得
GET http://localhost:8000/api/item
Accept: application/json

### ユーザー登録
POST https://api-juelhunter.japaneast.cloudapp.azure.com/api/users/store
Content-Type: application/json
Accept: application/json

{
    "name": "jobi2"
}

### ユーザー更新
POST http://localhost:8000/api/users/update
Content-Type: application/json
Accept:application/json

{
    "password": 6666
}

### フレンドリスト
GET  http://localhost:8000/api/friend/index
Content-Type: application/json
Accept:application/json


